### ISSUE TITLE
ownership on reactive-angular

### ISSUE THREAD

**Issue by hansschenker** [erdebee/homey-innova-ac#3]
Hi Roy,

you are the owner of reactive-angular repo.

I am Angular enthusiast and would like to code in Angular all the way reactive and mabe show the community
how Angular could be coded in a reactive style (mainly with the help of RxJs)

Question: would you give me the ownership on reactive-angular repo?

regards
Hans calling from switzerland
hans.schenker@windowslive.com

**Comment by erdebee** [comment]
Sorry for only reading this now, i invited you to be owner.

**Comment by hansschenker** [comment]
Hallo Roy,

thank's for the message and the invitation.
I saw that you started with AngularJs. For AngularJs was very hard to
learn. In fact I didn't get it.
I started with Angular which was much easier for me because of Typescript.
RxJs appealed to me because before I worked with C# and Linq which is close
to RxJs.

Thank's again and have a good time!
Hans
