### ISSUE TITLE
Will it be homey pro 2023 compatible?

### ISSUE THREAD

**Issue by pjmpessers** [erdebee/homey-innova-ac#5]
Hello Erdebee.

Like i said on your forum. Love your app. I stumbled on it when i googled for innova api. Didn't know it exist for homey. Works great on my old Homey pro 2019.
But i ordered the Homey pro 2023, so i wanted to know is it compatible with HP2023 (SDKv3)? or are you planning to make it compatible?
Will you bring this out to the homey app store. Because i don't think anybode else will know about this great app, until you search for it.
 And thanks again for this app.

**Comment by erdebee** [comment]
Working on SDK V3 conversion as we speak. Check the branch "sdkv3". This will probably make it compatible.
