### ISSUE TITLE
Red exclamation mark on device.

### ISSUE THREAD

**Issue by pjmpessers** [erdebee/homey-innova-ac#9]
Hello Roy. Great to see that this app arrived at the homey app store. Strange when i install it from the app store i get a red exclamation mark. 
There was no problem when i sideloaded the source code on the main branche.

If i try to sideloed the app-store-prep from the github branches i get these errors:

✓ Validating app...
Warning: flow.triggers['fan_speed_changed'].titleFormatted is missing. Specifying a Flow card's formatted title will be required in the future.
Warning: flow.triggers['thermostat_mode_changed'].titleFormatted is missing. Specifying a Flow card's formatted title will be required in the future.
Warning: flow.conditions['fan_speed_is'].titleFormatted is missing. Specifying a Flow card's formatted title will be required in the future.
Warning: flow.conditions['thermostat_mode_is'].titleFormatted is missing. Specifying a Flow card's formatted title will be required in the future.
Warning: flow.actions['fan_speed_set'].titleFormatted is missing. Specifying a Flow card's formatted title will be required in the future.
Warning: flow.actions['thermostat_mode_set'].titleFormatted is missing. Specifying a Flow card's formatted title will be required in the future.
✓ App validated successfully against level `debug`
✓ Packing Homey App...
 — App archive size: 1.1 MB, 31 files
✓ Installing Homey App on `Homey van ******` (http://192.168.1.***:***)...
✓ Homey App `nl.pulsive.innova` successfully installed

Maybe the same thing happens when i install it from the app store. Maybe it helps you to find the path to fix it?

P.S. The main branche still works and so i sideloaded that on my homey.

**Comment by Alxwin** [comment]
Great to have an Innova 2.0 app in the Homey appstore! Just got a Innova Mini installed. Tried adding it to Homey, but also got an exclamation mark when in the Select device screen. I will probably also get some Innova Airleafs, will they also be supported in the future?

**Comment by pjmpessers** [comment]
On this moment the main code works. If you know how to sideload it. I don't know what the difference is.

**Comment by Alxwin** [comment]
I haven't sideloaded any app on Homey yet. I already saw that the app wasn't in the appstore earlier. Today I wanted to check how the side loading works, but then found out that the app came live in de app store. Hopefully the app is fixed soon, so I don't need to sideload. :) No rush.

**Comment by pjmpessers** [comment]
From what i know the developer does support this app in his spare time, next to his private life and work. So maybe he get the change to fix the problem early. But maybe it will take some time. 
If you want to sideload it i could walk you thru.
Or like you said, just wait. ;-)
I can only say that for me it looks like the main code works flawless.

**Comment by pjmpessers** [comment]
New updated app solved the problem.
